apiVersion: v2
name: ejabberd
description: A Helm chart for installing the ejabberd messaging server on Kubernetes
type: application
version: 0.3.0
sources:
  - https://github.com/processone/ejabberd
icon: https://raw.githubusercontent.com/processone/docs.ejabberd.im/master/content/assets/img/footer_logo_e.png
keywords:
  - ejabberd
  - messaging
  - xmpp
  - mqtt
  - stun
  - turn
  - sip
  - matrix
