{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "limesurvey.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "limesurvey.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.existingSecret }}
  {{- if .Values.limesurvey.admin.password }}
  limesurvey-admin-password: {{ .Values.limesurvey.admin.password | b64enc | quote }}
  {{- else }}
  limesurvey-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.limesurvey.encrypt.keypair }}
  limesurvey-encrypt-keypair: {{ .Values.limesurvey.encrypt.keypair | b64enc | quote }}
  {{- end }}
  {{- if .Values.limesurvey.encrypt.publicKey }}
  limesurvey-encrypt-publicKey: {{ .Values.limesurvey.encrypt.publicKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.limesurvey.encrypt.secretKey }}
  limesurvey-encrypt-secretkey: {{ .Values.limesurvey.encrypt.secretKey | b64enc | quote }}
  {{- end }}
{{- end }}
